/*
 * Copyright (c) 1997, 2018, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graalvm_visualvm_lib_jfluid_server_system_GC */

#ifndef _Included_org_graalvm_visualvm_lib_jfluid_server_system_GC
#define _Included_org_graalvm_visualvm_lib_jfluid_server_system_GC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    activateGCEpochCounter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_activateGCEpochCounter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    resetGCEpochCounter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_resetGCEpochCounter
  (JNIEnv *, jclass);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    getCurrentGCEpoch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_getCurrentGCEpoch
  (JNIEnv *, jclass);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    objectsAdjacent
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_objectsAdjacent
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    getGCRelativeTimeMetrics
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_getGCRelativeTimeMetrics
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    getGCStartFinishTimes
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_getGCStartFinishTimes
  (JNIEnv *, jclass, jlongArray, jlongArray);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_GC
 * Method:    runGC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_GC_runGC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
