/*
 * Copyright (c) 1997, 2018, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graalvm_visualvm_lib_jfluid_server_system_Threads */

#ifndef _Included_org_graalvm_visualvm_lib_jfluid_server_system_Threads
#define _Included_org_graalvm_visualvm_lib_jfluid_server_system_Threads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    recordProfilerOwnThreads
 * Signature: (ZLjava/lang/Thread;)I
 */
JNIEXPORT jint JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_recordProfilerOwnThreads
  (JNIEnv *, jclass, jboolean, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    recordAdditionalProfilerOwnThread
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_recordAdditionalProfilerOwnThread
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    getTotalNumberOfThreads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_getTotalNumberOfThreads
  (JNIEnv *, jclass);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    suspendTargetAppThreads
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_suspendTargetAppThreads
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    resumeTargetAppThreads
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_resumeTargetAppThreads
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    terminateTargetAppThreads
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_terminateTargetAppThreads
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    targetAppThreadsExist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_targetAppThreadsExist
  (JNIEnv *, jclass);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    getAllThreads
 * Signature: ([Ljava/lang/Thread;)[Ljava/lang/Thread;
 */
JNIEXPORT jobjectArray JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_getAllThreads
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    getThreadsStatus
 * Signature: ([Ljava/lang/Thread;[I)V
 */
JNIEXPORT void JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_getThreadsStatus
  (JNIEnv *, jclass, jobjectArray, jintArray);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    getJVMArguments
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_getJVMArguments
  (JNIEnv *, jclass);

/*
 * Class:     org_graalvm_visualvm_lib_jfluid_server_system_Threads
 * Method:    getJavaCommand
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_graalvm_visualvm_lib_jfluid_server_system_Threads_getJavaCommand
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
